#!/usr/bin/env python3

M = 0
C = 1
B = 3

size = 6

class Canibals:
    def __init__(self):
        self.state = (int(size/2), int(size/2), False)
        self.visited = []

    def __repr__(self):
        rc = '🧟'
        rm = '🧔'
        rb = '🛥️'

        print(self.state)
        output = list([rm] * self.state[M] + [' '] * (int(size/2) - self.state[M]))
        output += list([rc] * self.state[C] + [' '] * (int(size/2) - self.state[C]))
        output += ['🌊']
        output += list([rm] * (int(size/2) - self.state[M]) + [' '] * self.state[M])
        output += list([rc] * (int(size/2) - self.state[C]) + [' '] * self.state[C])

        return "".join(output)

    def move(self, m=0, c=0):
        if m == 0 and c == 0:
            return False

        new_m = self.state[M] - m
        if new_m < 0:
            return False
        self.state[M] = new_m
        
        new_c = self.state[C] - c
        if new_c < 0:
            return False
        self.state[C] = new_c

        self.state[B] = not self.state[B]
        return True

    def valid_state(self):
        return self.state[M] >= self.state[C] 

    def final(self):
        return self.state[M] == 0 and self.state[C] == 0
        
    def search(self):

        possible_actions = ( (2, 0), (0, 2), (1, 1), (1, 0), (0, 1) )


        print(self)


if __name__=='__main__':

    print("Nyam Nyam")
    canibals = Canibals()

    canibals.search()

