#!/usr/bin/env python3

import sys

DEBUG = False
EMOJIS = True

representacio = {
    "pages": "🧑" if EMOJIS else "P",
    "oca": "🪿" if EMOJIS else "O",
    "llop": "🦊" if EMOJIS else "L",
    "blat": "🌾"if EMOJIS else "B",
}

SOLUCIONS = 0

class OcaLlopBlat():
    
    def __init__(self, estat=None, cami=None, solucio=None):
        """ Inicialitza l'estat, indicant cada cosa si esta a l'illa final o no """
        self.estat = estat or {
            "pages": False,
            "oca": False,
            "llop": False,
            "blat": False,
        }

        # Llistat de moviments
        self.solucio = solucio or []

        # Cami d'estats fins la solució
        self.cami = cami or []


    def __eq__(self, item):
        if DEBUG:
            print(f"Comparant: {self} i {item}")

        return self.estat == item.estat 


    def __contains__(self, item):
        if DEBUG:
            print(f"{item.estat}  dins  {self.cami}?")

        for element in self.cami:
            if element.estat == item.estat:
                return True
        return False


    def __repr__(self):

        output = list("    ~    ")
        
        if EMOJIS:
            output[4] = '🌊'

        elements = list(representacio.keys())

        for e in elements:
            posicio = elements.index(e) + (self.estat[e] * (len(elements) + 1))
            output[posicio] = representacio[e] 

        return "".join(output)
        

    def accio_transporta(self, element=None):
        """
        " Transporta l'element passat per paràmetre
        " o bé només el pages si no se passa cap elemet.
        """
        element = element or "pages"
    
        if DEBUG:
            print(f"Intentant transportar {element}")

        if self.estat["pages"] != self.estat[element]:
            if DEBUG:
                print(f"Falla! {element} no esta a la mateixa illa")

            return False

        self.estat["pages"] = not self.estat["pages"]

        if element != "pages":
            self.estat[element] = not self.estat[element]
            if DEBUG:
                print(f"Transportat {element} a {self.estat[element]}")
        else:
            if DEBUG:
                print(f"Transportat pages")

        return True


    def algu_menja_algu(self):
        """
        " Mira si algú s'ha menjat algú
        """
        llop = self.estat["llop"]
        oca = self.estat["oca"]
        pages = self.estat["pages"]
        blat = self.estat["blat"]

        if llop == oca and pages != llop and blat != llop:
            if DEBUG:
                print("Llop sol amb l'oca: nyam!")
            return True

        if oca == blat and pages != oca and llop != oca:
            if DEBUG:
                print("Oca sola amb blat: nyam!")
            return True

        if DEBUG:
            print("Ningu menja ningu")

        return False


    def final(self):
        """
        " Mira si hem arribat al final aconseguit l'objectiu
        """
        return False not in self.estat.values()


    def seguent(self):
        if DEBUG:
            print(f"Fent següents de {self}")

        for element in ["pages", "llop", "oca", "blat"]:
            # Important genera objectes nous dict, list per evitar
            # passar els punters ja que sinó als objecres següents
            # se modifiquen les referències.
            s = OcaLlopBlat(
                dict(self.estat),
                list(self.cami), 
                list(self.solucio),
            )
            if s.accio_transporta(element):

                carrega = representacio[element] if element != "pages" else ""

                if carrega == 'res' and not EMIJIS:
                    carrega = ""

                accio = f"🛥️  🧑{carrega}" if EMOJIS else f"duu {carrega}"

                s.solucio.append(accio)
                s.cami.append(self)

                if s.final():
                    s.solucio.append("🎊🎊🎊" if EMOJIS else "Final!")
                    s.cami.append(s)

                    global SOLUCIONS
                    SOLUCIONS += 1
                    print("ENHORABONA!")
                    print("Una solució és:")
                    for i in range(len(s.cami)):
                        entorn = s.cami[i]
                        moviment = s.solucio[i]
                        print(f"  {entorn}")
                        print(f"      {moviment}")
                        print("-------------------")
                    print("")
                    continue

                if self == s:
                    if DEBUG:
                        print("INVALID: Estat invalid no hi ha moviment")
                    continue

                if s.algu_menja_algu():
                    if DEBUG:
                        print("INVALID: Algu es menjat")

                    continue

                if s in self:
                    if DEBUG:
                        print("INVALID: Estat repetit")

                    continue

                s.seguent()


if __name__=='__main__':
    print("""Oca llop blat

Un pages esta a una illa on hi ha una oca, un llop i blat.

Tots han de creuar a l'altre illa.

El pages és l'unic que pot dur la barca i només pot transportar una cosa a la vegada.

Si el llop queda sol amb l'oca se la menja.

Si l'oca queda sola amb el blat se'l menja.

Es possible que tots creuin? Com?
    """)

    olb = OcaLlopBlat()
    olb.seguent()

    print(f"S'han trobat {SOLUCIONS} solucuons.")
