#!/usr/bin/env python3

from copy import deepcopy

class OcaLlopBlat():
    
    def __init__(self):
        """ Inicialitza l'estat, indicant cada cosa si esta a illa 0 o 1"""
        self.estat = {
            "pages": 0,
            "llop": 0,
            "oca": 0,
            "blat": 0,
        }

        self.cami = []

    def __eq__(a, b):
        print(f"Comparant: {a} i {b}")
        for personatge in a.estat.keys():
            if a.estat[personatge] != b.estat[personatge]:
                print("Son diferents")
                return False

        print("Son iguals")
        return True


    def __contains__(a, b):
        for estat in a.cami:
            if estat == b:
                return True
        return False


    def __repr__(self):

        output = ""

        for element, illa in self.estat.items():
            if illa == 0:
                output += element[0].upper() + ""

        output += "~"
        for element, illa in self.estat.items():
            if illa == 1:
                output += element[0].upper() + ""

        return output
        

    def accio_transporta(self, element=None):
        """
        " Transporta l'element passat per paràmetre
        " o bé només el pages si no se passa cap elemet.
        """
        element = element or "pages"

        print(f"Intentant transportar {element}")
        if self.estat["pages"] != self.estat[element]:
            print(f"Falla! {element} no esta a la mateixa illa")
            return False

        self.estat["pages"] = not self.estat["pages"]
        if element != "pages":
            self.estat[element] = not self.estat[element]
            print(f"Transportat {element} a {self.estat[element]}")
        else:
            print(f"Transportat pages")

        return True


    def seguent(self):
        print(f"Fent següent de {self}")
        for element in ["pages", "llop", "oca", "blat"]:
            print(element)
            s = deepcopy(self)
            if s.accio_transporta(element):
                if self != s:
                    if s not in self:
                        if s.ningu_menja_ningu():
                            s.cami.append(s)
                            if s.final():
                                print("Arribat!")
                            print("No es final")
                            return s.seguent()
                        print("A")
                    print("B")
                print("C")
            print("D")

                    
    def ningu_menja_ningu(self):
        """
        " Mira si algú s'ha menjat algú
        """
        llop = self.estat["llop"]
        oca = self.estat["oca"]
        pages = self.estat["pages"]
        blat = self.estat["blat"]

        if llop == oca and pages != llop and blat != llop:
            print("Llop sol amb l'oca: nyam!")
            return False

        if oca == blat and pages != oca and llop != oca:
            print("Oca sola amb blat: nyam!")
            return False

        print("Ningu menja ningu")
        return True


    def final(self):
        """
        " Mira si hem arribat al final aconseguit l'objectiu
        """
        return 0 not in self.estat.values()





if __name__=='__main__':
    print("""Oca llop blat

Un pages esta a una illa on hi ha una oca una llop i blat.

Tots han de creuar a l'altre illa.

El pages es l'unic que pot dur la barca i només pot transportar una cosa a la vegada.

Si el llop queda sol amb l'oca se la menja.

Si l'oca queda sola amb el blat se'l menja.

Es possible que tots creuin? Com?
    """)

    olb = OcaLlopBlat()

    print(olb)
    olb.seguent()



